# application.properties

# Base de datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sorteoapp}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

# JWT
spring.jwt.secret=${SPRING_JWT_SECRET:mi_super_clave_jwt_segura_1234567890}



# Puerto del servidor
server.port=${PORT:8080}

