services:
  - type: web
    name: sorteo-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        value: jdbc:postgresql://dpg-d3hbidm3jp1c73fe19dg-a.oregon-postgres.render.com:5432/sorteoapp
      - key: DB_USERNAME
        value: postgress
      - key: DB_PASSWORD
        value: ARV8b8suHHgnBcuAn1JY8uWV4aqwlhYR
      - key: JWT_SECRET
        value: P@sc4l_4l4n_Tur1nG!J0hnV0nN3um4nn#F3rm4t_Eul3r2025$
