services:
  - type: web
    name: sorteo-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod   # <-- activa el perfil de producción
      - key: PORT
        value: 8080
      - key: DB_URL
        value: jdbc:postgresql://dpg-d4rih16mcj7s738722c0-a.oregon-postgres.render.com:5432/sorteoapp_7ace
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: yAXrPhqhelVLLFyRykR6GuLAny4Kd4sZ
      - key: JWT_SECRET
        value: P@sc4l_4l4n_Tur1nG!J0hnV0nN3um4nn#F3rm4t_Eul3r2025$
