services:
  - type: web
    name: sorteo-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod   # <-- activa el perfil de producción
      - key: PORT
        value: 8080
      - key: DB_URL
        value: postgresql://sorteoapp_jgkm_user:NWn19qvZnhatIb0CMwnePdsUn2NiP7Aw@dpg-d4rjpp4hg0os73ap1hq0-a/sorteoapp_db
      - key: DB_USERNAME
        value: postgress
      - key: DB_PASSWORD
        value: NWn19qvZnhatIb0CMwnePdsUn2NiP7Aw
      - key: spring.jwt.secret
        value: P@sc4l_4l4n_Tur1nG!J0hnV0nN3um4nn#F3rm4t_Eul3r2025$
